### PR TITLE
Add CMake build system and update README.md

### PR DESCRIPTION
**Pull request by jopadan**

### CODE REVIEW

**Comment by dotted** [comment]
Is there a reason you keep making new pull requests?

**Comment by jopadan** [comment]
The intention is to reduce the commit log to one or two.
I won't open another one. Are you able to build and run it now?

**Comment by dotted** [comment]
PRs usually get squashed before merge, so don't worry about the commit log. I'll try and build when I get home from work in about 4 hours.

**Comment by dotted** [comment]
Doesn't compile, seems you forgot to add the examples to the commit after moving their directories, causing them to be deleted instead.

**Comment by jopadan** [comment]
Examples are now committed again by prepending ./ in .gitignore

**Comment by dotted** [comment]
➜  ADiKtEd git:(pr-47) ✗ git clean -dfX && cmake . && cmake --build .
```
[ 63%] Linking C executable puttrain
/usr/bin/ld: libadikted/libadikted.so: undefined reference to `ceil'
/usr/bin/ld: libadikted/libadikted.so: undefined reference to `acos'
/usr/bin/ld: libadikted/libadikted.so: undefined reference to `sin'
/usr/bin/ld: libadikted/libadikted.so: undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/puttrain.dir/build.make:87: puttrain] Error 1
make[1]: *** [CMakeFiles/Makefile2:177: CMakeFiles/puttrain.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by jopadan** [comment]
I rebased and squashed the commits fixing the mentioned bugs

**Comment by dotted** [comment]
Continued in #48

**Pull request closed without merging**
