### PR TITLE
make file moved and fixed

### PR DESCRIPTION
**Pull request by SimLV**

### CODE REVIEW

**Comment by dotted** [comment]
You have made changes to `libadikted/Makefile` can you make sure it's in sync with `libadikted/Makefile.win` as that file has been updated to let it compile with GCC 9.2.0. Better yet, merge the files so we don't have an issue of those go out of sync in the future.

**Comment by eddebaby** [comment]
> You have made changes to `libadikted/Makefile` can you make sure it's in sync with `libadikted/Makefile.win` as that file has been updated to let it compile with GCC 9.2.0. Better yet, merge the files so we don't have an issue of those go out of sync in the future.

I'll action this ASAP dotted.

For reference, Sim now has both `libadikted/Makefile` and `mapslang/Makefile` in a state where one can build map.exe (and libslang.dll/adikted.dll) using MSYS2 (MinGW32).

**Comment by dotted** [comment]
@eddebaby I used MSYS2, are you telling make to make use of the Makefile.win by using `make -f Makefile.win`?

**Comment by eddebaby** [comment]
I thought I did that @dotted, but I can't remember. 
However, just knowing you used MSYS2 is enough for me, I'll work out any issues/differences.

**Comment by dotted** [comment]
@SimLV Let me know when you are ready to have your PR merged and I'll get that sorted. I'm moving the merging of the Makefiles into a separate issue see #3.

**Comment by SimLV** [comment]
I am done with this PR so if you want to make some changes you may branch from it

**Pull request merged**
